project:
  type: website
  output-dir: docs



website:
  title: "Ryan Block"
  navbar:
    search: false
    background: "#325d88"
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: Vita
      - icon: envelope
        href: mailto:rjb14@rice.edu
      - text: "{{< fa brands bluesky>}}"
        href: https://bsky.app/profile/ryanjblock.bsky.social
  page-footer:
    background: light
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/ryanjblock/ryanjblock.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

  
format:
  html:
    theme: 
      - sandstone
      - html/styles.scss
    mainfont: Montserrat
    fontsize: 1.1em
    linkcolor: "#ff33f0"
    css: styles.css
    toc: false

  
# Site Author
# author:
#   name: "Ryan Block"
#   avatar: "headshot.png"
#   bio: "Ph.D. Student"
#   email:  #rjb14@rice.edu
#   employer: 'Rice University'
#   location: "Houston, TX"
#   googlescholar:
#   researchgate:
#   uri:
#   bitbucket:
#   codepen:
#   github: #"ryanjblock"
#   orcid: #"http://orcid.org/yourorcidurl"
#   stackoverflow: # http://stackoverflow.com/users/123456/username
#   twitter: #RyanJBlock
#   youtube:
#   wikipedia:


        
        


