
---
title: "Research"
permalink: /research/
---

## Peer-Reviewed Articles

Peterson, Erik, Shannon C. McGregor, and **Ryan Block**. 2025. ["Election Denial as a News Coverage Dilemma: A Survey Experiment with Local Journalists."](https://www.tandfonline.com/doi/full/10.1080/10584609.2025.2456524){target=_blank} *Political Communication*, 1-20.

## Under Review

"Partisan Identity in Multi-Party Democracies" (Book manuscript with Randolph Stevenson and Seonghui Lee)

"Divided by Partisanship: Uncovering Young Men’s and Young Women’s Attachments to the Radical Right" (with Gonzalo Di Landro)

## Works in Progress

"The Influence of Multiple Partisan Attachments on Economic Perceptions in Multi-Party Democracies"

"Strategic Voting and the Information Environment" (with Gonzalo Di Landro)

"Partisan Cooperation, Coalitions, and Multi-Party Partisanship" (with Sho Izumisawa)

"Does Support from Overlapping Social Groups Structure Multi-Party Identity in Multi-Party Systems?"

"The Evolution of Partisan Attachments in Western Europe"

“Does the Lack of non-English Language Papers in Meta-Analysis Bias Their Results?” (with Sho Izumisawa, Mohammed Abduljabbar, Cinthia Dalcin, Guillermo Martinez, Agustin Prinetti, and Yucheng Xue)
