---
title: "Teaching"
permalink: /teaching/
---

## TA Experience

### Graduate Courses

**Introduction to Statistics (Fall 2023)**  
*Prof. Matthew Tyler*  
⭐️⭐️⭐️⭐️️⭐️(5/5)

**Causal Inference (Spring 2024)**  
*Prof. Erik Peterson*  
️⭐️⭐️⭐️⭐️️⭐️(5/5)

**Maximum Likelihood Estimation (Fall 2024)**  
*Prof. Randy Stevenson*  
⭐️⭐️⭐️⭐️️⭐️(5/5) 

**Measurement and Research Design (Spring 2025)**  
*Prof. Randy Stevenson*  
*In progress*

---

## Select Reviews From Students

> *"Ryan was very helpful when I was struggling or lost. He often took the time to explain things in depth, which helped point me in the right direction on the homework. Ryan is also very patient and understanding when I didn't get something the first time and needed something repeated. Ryan was also willing to make time to answer quick follow-up questions outside of his office hours if I sent him an email or stuck my head in his office."*

> *"Ryan is a great TA; he always helped clarify difficult material, provided useful resources, and offered insightful feedback on assignments."*

> *"Ryan helped a lot whenever I needed clarification regarding the problems in the question-sets or assistance in how should I proceed with the codes for the analysis. He shared ideas on how should I start thinking about / approach the question when I struggled with finding a starting point to think about how I can analyze the data. Overall, I think his performance as the TA was highly effective."*

> *"Ryan didn't hesitate to help. He clarified my confusion and encouraged me to do my best."*

> *"Ryan was an extremely effective and helpful TA. During his office hours, and even outside of them if he had the time, he was always willing to help and ensure that we actually learned the concept at hand rather than just give us the answers. While [the instructor] was effective as a professor on his own, Ryan further enhanced the ability of us students to grasp these subjects and succeed in this class."*